### ISSUE TITLE
Define library for connect with vk api

### ISSUE THREAD

**Issue by anton-shumakov** [anton-shumakov/YASNA#3]

**Comment by anton-shumakov** [comment]
# vk_api

https://pypi.org/project/vk-api/

This library has kinda alive telegram chat, some commits in github from not so long time ago and good enough documentation.

# aiovk

asynchronous, has not documentation.

# vkwave, LiteVkApi, vkbottle 

in discussion about alternative to vk_api - https://github.com/python273/vk_api/issues/356

**Comment by anton-shumakov** [comment]
# LiteVkApi 

kinda poor

# vkwave

asynchronous, customizable, has documentation, but not so fast, as written in Readme file

#vkbottle

asynchronous, customizable, has documentation

**Comment by anton-shumakov** [comment]
# Result

I research interesting, but so we don't need to implement bot stuff, aiovk - is a good solution.

**Comment by iliya-b** [comment]
vk_api has 
more contributors
more stars
~~more issues~~


It is more stable and can be (should be) used in a serious solution

**Comment by iliya-b** [comment]
resolved: we use https://pypi.org/project/vk-api/
